---
services:
  webserver:
    image: nginx
    container_name: con2
    ports:
      - "8001:80"
    volumes:
      - /test:/usr/share/nginx/html
    environment:
      - NGINX=production

---
services:
  ci_cd:
    image: jenkins/jenkins
    container_name: con2
    ports:
      - "8080:8080"
    environment:
      - jenkins.env

  webserver2:
    image: httpd
    container_name: con3
    ports:
      - "8081:80"
    volumes:
      - myvol1:/usr/local/apache2/htdocs
    environment:
      - APACHE2=staging
volumes:
  myvol1:
    name: v1
